theme: jekyll-theme-minimal
title: Paul Brejla
logo: /assets/img/1612694489876.jpeg
description:  Software Engineer, Requirements Engineer (CPRE-A, TÜV), Software Architect (CPSA-F, ISQI), Business Analyst & Published Researcher - welcome to my personal Web site!
