theme: jekyll-theme-minimal
title: Paul Brejla
logo: /assets/img/paul.jpg
description:  Software Engineer, Software Architect, Business Analyst & Published Researcher - welcome to my personal Web site!
